<a href="https://colab.research.google.com/github/Zironics/weatherApp2/blob/main/rayleigh.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
def rayleigh_quot(A,X):
    D = X.T @ A @ X
    Q = norme_euclid(X)**2
    return D/Q

In [ ]:
def norme_euclid(M):
    M = np.array(M)
    return np.sqrt(np.max(np.linalg.eig(M@M.T)[0]))

In [ ]:
def X_iter(A,X):
    D = A @ X
    Q = norme_euclid(A @ X)
    return (D/Q).reshape(3,1)

In [ ]:
def is_invert(M):
    print(M)
    print(f"determinant : {np.linalg.det(M)}")
    if np.linalg.det(M) == 0: 
        return False
    return True

In [ ]:
def rayleigh_iter(A,B):
    X = B
    n = 0
    while(True):
        n += 1;
        print(n)
        v = rayleigh_quot(A,X)[0]
        Y = A-v*np.identity(A.shape[0])
        if not is_invert(Y):
            return v, Y
        M = np.linalg.inv(Y)
        X = X_iter(M,X)

In [ ]:
A = np.array([[1,2,3],[1,2,1],[3,2,1]])
B = np.array([[1],[1],[1]])
v,Y = rayleigh_iter(A,B)

1
[[-4.33333333  2.          3.        ]
 [ 1.         -3.33333333  1.        ]
 [ 3.          2.         -4.33333333]]
determinant : -3.2592592592592733
2
[[-4.24183007  2.          3.        ]
 [ 1.         -3.24183007  1.        ]
 [ 3.          2.         -4.24183007]]
determinant : -0.1868540031388739
3
[[-4.23607548  2.          3.        ]
 [ 1.         -3.23607548  1.        ]
 [ 3.          2.         -4.23607548]]
determinant : -0.000242798325391703
4
[[-4.23606798  2.          3.        ]
 [ 1.         -3.23606798  1.        ]
 [ 3.          2.         -4.23606798]]
determinant : -4.074474105400875e-10
5
[[-4.23606798+0.j  2.        +0.j  3.        +0.j]
 [ 1.        +0.j -3.23606798+0.j  1.        +0.j]
 [ 3.        +0.j  2.        +0.j -4.23606798+0.j]]
determinant : (-3.213459710549226e-14+0j)
6
[[-4.23606798+0.j  2.        +0.j  3.        +0.j]
 [ 1.        +0.j -3.23606798+0.j  1.        +0.j]
 [ 3.        +0.j  2.        +0.j -4.23606798+0.j]]
determinant : 0j


array([[-4.23606798+0.j,  2.        +0.j,  3.        +0.j],
       [ 1.        +0.j, -3.23606798+0.j,  1.        +0.j],
       [ 3.        +0.j,  2.        +0.j, -4.23606798+0.j]])

In [ ]:
print(v)

(5.23606797749979+0j)


In [ ]:

M = np.array([[-4.23606798+0.j,  2.        +0.j,  3.        +0.j],
       [ 1.        +0.j, -3.23606798+0.j,  1.        +0.j],
       [ 3.        +0.j,  2.        +0.j, -4.23606798+0.j]])
 
d = np.linalg.det(M)
print(d)
print(np.linalg.det(M))

(-8.090849183362344e-08+0j)
(-8.090849183362344e-08+0j)


In [ ]:
is_invert(M)

(-8.090849183362344e-08+0j)


True